name             'dev'
maintainer       'Yuichi Takeuchi'
maintainer_email 'info@takeyu-web.com'
license          'All rights reserved'
description      'Installs/Configures base'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'
depends          'mysql'
depends          'database'
depends          'imagemagick'
depends          'cpan'
depends          'ark'
